/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Class {
  'id' : Id,
  'active' : boolean,
  'name' : string,
  'description' : string,
}
export interface Course {
  'id' : Id,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'classId' : Id,
}
export type ExternalBlob = Uint8Array;
export interface GetSubscriptionConfig {
  'priceSatoshis' : bigint,
  'qrImage' : [] | [ExternalBlob],
  'paywallEnabled' : boolean,
}
export type Id = string;
export interface Lesson {
  'id' : Id,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'classId' : Id,
  'videoSource' : VideoSource,
  'videoUrl' : string,
  'courseId' : [] | [Id],
}
export interface LessonProgress {
  'lessonId' : Id,
  'completed' : boolean,
  'completionTimestamp' : [] | [bigint],
}
export interface Student {
  'id' : Id,
  'principal' : Principal,
  'active' : boolean,
  'classId' : Id,
  'lastName' : string,
  'courseId' : [] | [Id],
  'firstName' : string,
}
export interface Teacher {
  'id' : Id,
  'principal' : Principal,
  'active' : boolean,
  'lastName' : string,
  'firstName' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoSource = { 'uploaded' : null } |
  { 'external' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateClassSubscription' : ActorMethod<[Id, Id], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[string, string], Id>,
  'createCourse' : ActorMethod<[Id, string, string], Id>,
  'createLesson' : ActorMethod<
    [string, string, Id, [] | [Id], VideoSource, string],
    Id
  >,
  'getAllProgressForStudent' : ActorMethod<[Principal], Array<LessonProgress>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassSubscriptionConfig' : ActorMethod<
    [Id],
    [] | [GetSubscriptionConfig]
  >,
  'getClasses' : ActorMethod<[], Array<Class>>,
  'getCourseProgress' : ActorMethod<
    [Id],
    Array<[Principal, Array<LessonProgress>]>
  >,
  'getCourseProgressForStudent' : ActorMethod<
    [Principal, Id],
    Array<LessonProgress>
  >,
  'getCourses' : ActorMethod<[[] | [Id]], Array<Course>>,
  'getLessonProgress' : ActorMethod<[Id], [] | [LessonProgress]>,
  'getLessons' : ActorMethod<[[] | [Id], [] | [Id]], Array<Lesson>>,
  'getMyStudentProfile' : ActorMethod<[], [] | [Student]>,
  'getMyTeacherProfile' : ActorMethod<[], [] | [Teacher]>,
  'getProgressForLesson' : ActorMethod<
    [Id],
    Array<[Principal, LessonProgress]>
  >,
  'getStudents' : ActorMethod<[[] | [Id], [] | [Id]], Array<Student>>,
  'getTeachers' : ActorMethod<[], Array<Teacher>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasClassSubscription' : ActorMethod<[Id, Id], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudent' : ActorMethod<
    [Principal, string, string, Id, [] | [Id]],
    Id
  >,
  'registerTeacher' : ActorMethod<[Principal, string, string], Id>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setClassSubscriptionConfig' : ActorMethod<
    [Id, boolean, bigint, ExternalBlob],
    undefined
  >,
  'updateLessonProgress' : ActorMethod<[Id, boolean, [] | [bigint]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];