/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Id = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoSource = IDL.Variant({
  'uploaded' : IDL.Null,
  'external' : IDL.Null,
});
export const LessonProgress = IDL.Record({
  'lessonId' : Id,
  'completed' : IDL.Bool,
  'completionTimestamp' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GetSubscriptionConfig = IDL.Record({
  'priceSatoshis' : IDL.Nat,
  'qrImage' : IDL.Opt(ExternalBlob),
  'paywallEnabled' : IDL.Bool,
});
export const Class = IDL.Record({
  'id' : Id,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : Id,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'classId' : Id,
});
export const Lesson = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'classId' : Id,
  'videoSource' : VideoSource,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Opt(Id),
});
export const Student = IDL.Record({
  'id' : Id,
  'principal' : IDL.Principal,
  'active' : IDL.Bool,
  'classId' : Id,
  'lastName' : IDL.Text,
  'courseId' : IDL.Opt(Id),
  'firstName' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : Id,
  'principal' : IDL.Principal,
  'active' : IDL.Bool,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateClassSubscription' : IDL.Func([Id, Id], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
  'createCourse' : IDL.Func([Id, IDL.Text, IDL.Text], [Id], []),
  'createLesson' : IDL.Func(
      [IDL.Text, IDL.Text, Id, IDL.Opt(Id), VideoSource, IDL.Text],
      [Id],
      [],
    ),
  'getAllProgressForStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassSubscriptionConfig' : IDL.Func(
      [Id],
      [IDL.Opt(GetSubscriptionConfig)],
      ['query'],
    ),
  'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getCourseProgress' : IDL.Func(
      [Id],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LessonProgress)))],
      ['query'],
    ),
  'getCourseProgressForStudent' : IDL.Func(
      [IDL.Principal, Id],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getCourses' : IDL.Func([IDL.Opt(Id)], [IDL.Vec(Course)], ['query']),
  'getLessonProgress' : IDL.Func([Id], [IDL.Opt(LessonProgress)], ['query']),
  'getLessons' : IDL.Func(
      [IDL.Opt(Id), IDL.Opt(Id)],
      [IDL.Vec(Lesson)],
      ['query'],
    ),
  'getMyStudentProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getMyTeacherProfile' : IDL.Func([], [IDL.Opt(Teacher)], ['query']),
  'getProgressForLesson' : IDL.Func(
      [Id],
      [IDL.Vec(IDL.Tuple(IDL.Principal, LessonProgress))],
      ['query'],
    ),
  'getStudents' : IDL.Func(
      [IDL.Opt(Id), IDL.Opt(Id)],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'getTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasClassSubscription' : IDL.Func([Id, Id], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, Id, IDL.Opt(Id)],
      [Id],
      [],
    ),
  'registerTeacher' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [Id], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setClassSubscriptionConfig' : IDL.Func(
      [Id, IDL.Bool, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'updateLessonProgress' : IDL.Func([Id, IDL.Bool, IDL.Opt(IDL.Int)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Id = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoSource = IDL.Variant({
    'uploaded' : IDL.Null,
    'external' : IDL.Null,
  });
  const LessonProgress = IDL.Record({
    'lessonId' : Id,
    'completed' : IDL.Bool,
    'completionTimestamp' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GetSubscriptionConfig = IDL.Record({
    'priceSatoshis' : IDL.Nat,
    'qrImage' : IDL.Opt(ExternalBlob),
    'paywallEnabled' : IDL.Bool,
  });
  const Class = IDL.Record({
    'id' : Id,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : Id,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'classId' : Id,
  });
  const Lesson = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'classId' : Id,
    'videoSource' : VideoSource,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Opt(Id),
  });
  const Student = IDL.Record({
    'id' : Id,
    'principal' : IDL.Principal,
    'active' : IDL.Bool,
    'classId' : Id,
    'lastName' : IDL.Text,
    'courseId' : IDL.Opt(Id),
    'firstName' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : Id,
    'principal' : IDL.Principal,
    'active' : IDL.Bool,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateClassSubscription' : IDL.Func([Id, Id], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
    'createCourse' : IDL.Func([Id, IDL.Text, IDL.Text], [Id], []),
    'createLesson' : IDL.Func(
        [IDL.Text, IDL.Text, Id, IDL.Opt(Id), VideoSource, IDL.Text],
        [Id],
        [],
      ),
    'getAllProgressForStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassSubscriptionConfig' : IDL.Func(
        [Id],
        [IDL.Opt(GetSubscriptionConfig)],
        ['query'],
      ),
    'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getCourseProgress' : IDL.Func(
        [Id],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LessonProgress)))],
        ['query'],
      ),
    'getCourseProgressForStudent' : IDL.Func(
        [IDL.Principal, Id],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getCourses' : IDL.Func([IDL.Opt(Id)], [IDL.Vec(Course)], ['query']),
    'getLessonProgress' : IDL.Func([Id], [IDL.Opt(LessonProgress)], ['query']),
    'getLessons' : IDL.Func(
        [IDL.Opt(Id), IDL.Opt(Id)],
        [IDL.Vec(Lesson)],
        ['query'],
      ),
    'getMyStudentProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getMyTeacherProfile' : IDL.Func([], [IDL.Opt(Teacher)], ['query']),
    'getProgressForLesson' : IDL.Func(
        [Id],
        [IDL.Vec(IDL.Tuple(IDL.Principal, LessonProgress))],
        ['query'],
      ),
    'getStudents' : IDL.Func(
        [IDL.Opt(Id), IDL.Opt(Id)],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasClassSubscription' : IDL.Func([Id, Id], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, Id, IDL.Opt(Id)],
        [Id],
        [],
      ),
    'registerTeacher' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [Id], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setClassSubscriptionConfig' : IDL.Func(
        [Id, IDL.Bool, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'updateLessonProgress' : IDL.Func([Id, IDL.Bool, IDL.Opt(IDL.Int)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };